name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  solidity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run formatter check
        run: forge fmt --check src/

      - name: Run linter
        run: forge lint src/
