name: test

on:
  push:
    branches:
    - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge lint
        run: forge lint src/

      - name: Run unit tests
        run: forge test -vv --no-match-contract Fork

      - name: Run fork tests
        run: forge test -vv --match-contract Fork --fork-url ${{ secrets.ETH_RPC_URL }}
